service: n7m
provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-1
  stage: production
functions:
  main:
    handler: handler.main
    events:
      - http:
          path: /
          method: get
      - http:
          path: /{word}
          method: get
